name: case_event
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - tensorflow=2
  - keras
  - flake8
  - librosa
  - matplotlib
  - pydub
  - ffmpeg
platforms:
  - linux-64
  - win-64
